### ISSUE TITLE
I am not able to upload images to the editor

### ISSUE THREAD

**Issue by DarshPareek** [Tnxec2/amazfit-gts2mini-watchface-react#1]

**Comment by Tnxec2** [comment]
can you provide more information, what exactly doesn't work.

Wenn you click on Load Images Button, you should select all images for your watschface _at once._ You can select all images for example with Cntrl+A. And then open.

All images for Watchface should have valid numeric names, for example 0000.png, 0001.png, 2.png, 03.png... With or without zeros at the beginning. Number sequences can also be interrupted, for ex. 0, 1, 2, 10-19, 40-49, 100-121, 200, 300 etc.

**Comment by DarshPareek** [comment]
so i was not aware of the filename thing and now i am able to upload images. Is there a discord or slack where i can learn about how to make animations work etc.

**Comment by Tnxec2** [comment]
No, i dont have documentation for my program. But you can unpack some
watchfaces with parser, and see how things work.

Or you can ask me.

DarshPareek ***@***.***> schrieb am Sa., 11. Mai 2024, 13:46:
